ARDUINO_DIR = /usr/share/arduino
BOARD_TAG = uno
MONITOR_PORT = /dev/ttyACM0
ARDUINO_PORT = /dev/ttyACM0
ARDUINO_LIBS = OneWire DallasTemperatureControl FreqCounter
include /usr/share/arduino/Arduino.mk
